;[env:pico]
;platform = https://github.com/maxgerhardt/platform-raspberrypi.git
;board = pico
;framework = arduino
;board_build.core = earlephilhower
;board_build.filesystem = littlefs
;board_build.filesystem_size = 1m

;lib_deps = 
;https://github.com/Vicharak-in/shrike_arduino.git

[env:pico]
; This specific URL includes the fix for the missing build script
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower

; Reserves space for your FPGA bitstream (Step 7)
board_build.filesystem = littlefs
board_build.filesystem_size = 1m
lib_ldf_mode = deep+
build_flags = -I lib/Shrike

lib_deps = 
    https://github.com/vicharak-in/shrike_arduino.git   

